apiVersion: v1
kind: ConfigMap
metadata:
  name: nexo-config
  namespace: nexo
data:
  API_ADDR: ':8080'
  DB_POOL_MAX: '10'
  PARTITION_COUNT: '4'
  STATIC_DIR: /app/src/nexo/static
  S3_BUCKET: nexo-files
  AWS_REGION: us-east-1
  SFTP_ADDR: simulator.card-network.svc.cluster.local:2222
  SFTP_USER: nexo
  SFTP_KNOWN_HOSTS: /run/secrets/known_hosts
  BATCH_MAX_ROWS: '1000'
  SCHEDULE_MAX_BATCHES: '200'
  WORKER_POLL_SECONDS: '5'
