apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - config.yaml
  - api.yaml
  - worker.yaml
  - scheduler.yaml
  - migration.yaml
  - simulator.yaml
  - network-policy.yaml
